### ISSUE TITLE
Check when input is empty

### ISSUE THREAD

**Issue by koolamusic** [muthomiBrian/clarity#1]
when user does not provide input, the data is entered and allows for user to make empty inputs. 

### Possible Solution
Check if user has made any input, or set a character limit within the input box before data can be collected.

![Screenshot_2019-03-25 Clarity](https://user-images.githubusercontent.com/8960757/54912235-84e18300-4ef0-11e9-87c1-5be5d86b7e4b.png)

**Comment by muthomiBrian** [comment]
Thanks, let me add validation to help users avoid empty inputs.

**Comment by koolamusic** [comment]
Perfect

**Comment by muthomiBrian** [comment]
I updated the input to check if its empty and added some validation.
